config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { sessions: "accounts/sessions",
    registrations: 'accounts/registrations' }

  match '/save_expenditure',  to: 'budgets#save_expenditure',  via: :post, as: :save_expenditure
  match '/save_revenue',  to: 'budgets#save_revenue',  via: :post, as: :save_revenue
  match '/approve_payment_voucher',  to: 'payment_vouchers#approve',  via: :post, as: :approve_payment_voucher
  match '/approve_petty_cash',  to: 'petty_cash_vouchers#approve',  via: :post, as: :approve_petty_cash
  match '/authorize_payment_voucher',  to: 'payment_vouchers#authorize',  via: :post, as: :authorize_payment_voucher
  match '/authorize_petty_cash',  to: 'petty_cash_vouchers#authorize',  via: :post, as: :authorize_petty_cash
  match '/accounting',  to: 'dashboard#index',  via: :get, as: :accounting_index

  root 'dashboard#index'
  resources :dashboard, only: [:index]
  resources :roles
  resources :financial_years do
    resources :budgets
    resources :revenues
    resources :petty_cash
    resources :petty_cash_vouchers
    resources :payment_vouchers
    resources :vouchers
  end
  resources :bank_accounts
  resources :code_categories do
    resources :codes do
      resources :sub_codes
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/petty_cash.rb
class PettyCash < ApplicationRecord
  belongs_to :financial_year
  belongs_to :payment_voucher
  has_many :petty_cash_vouchers
end

app/controllers/petty_cash_controller.rb
class PettyCashController < ApplicationController
  before_action :set_paper_trail_whodunnit
  
  def index
    @petty_cash = PettyCash.order(created_at: :desc).where(financial_year_id: @current_financial_year.id)
  end

  def new
    @petty_cash = PettyCash.new
  end

  def create
    @petty_cash = PettyCash.new(petty_cash_params)
    if @petty_cash.save
      flash[:success] = "Successfully Re-imbursed Petty Cash"
      notes = "Re-imbursed a petty Cash => id: #{@petty_cash.id}"
      create_log('create', @petty_cash, notes)
      respond_to do |format|
        format.html { redirect_to financial_year_petty_cash_path(@current_financial_year,@petty_cash)}
      end
    else
      flash[:error] = "Sorry please try again"
      puts @petty_cash.errors.full_messages.to_sentence
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def show
    @petty_cash = PettyCash.find(params[:id])
  end

  private

  def petty_cash_params
    params.require(:petty_cash).permit(:financial_year_id, :amount, :amount_in_words, :payment_voucher_id)
  end
end

app/helpers/petty_cash_helper.rb
module PettyCashHelper
end

app/views/petty_cash/index.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="panel">
       <div class="panel-body">
         <%= link_to 'Petty Cash Payments', financial_year_petty_cash_vouchers_path(@current_financial_year) , class: 'btn btn-lg btn-primary' %>
         <%= link_to 'Re-Imburse', new_financial_year_petty_cash_path(@current_financial_year) , class: 'btn btn-lg btn-success' %>
       </div>
     </div>
   </div>
   <div class="col-md-12">
     <div class="panel">
       <header class="panel-heading">
         <h2 class="panel-title">Petty Cash Re-Imbursements</h2>
       </header>
       <div class="panel-body">
         <div class="table-responsive">
           <table class="table table-bordered table-hover table-striped">
             <thead>
               <tr>
                 <th>#</th>
                 <th>Amount</th>
                 <th>Created By</th>
                 <th>Approved By</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <!--  Make sure that all vouchers are only for the current year -->
               <% @petty_cash.order(created_at: :desc).each do |petty_cash| %>
                 <tr>
                   <td>#</td>
                   <td><%= currency_formatter(petty_cash.amount) %></td>
                   <td><%= find_account(petty_cash.payment_voucher.voucher.created_by) %></td>
                   <td><%= find_account(petty_cash.payment_voucher.voucher.approved_by) %></td>
                   <td><%= link_to "View", financial_year_petty_cash_path(@current_financial_year, petty_cash) %></td>
                 </tr>
               <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/petty_cash/new.html.erb
<div class="col-xs-12 col-sm-offset-3 col-sm-5">
    <div class="panel">
        <header class="panel-heading">
            <h2 class="panel-title text-center">Petty Cash</h2>
        <div class="panel-body">
          <%= form_for @petty_cash, url: {action: "create"}, html: {id: 'payment-form', class: "form-horizontal"} do |f| %>
            <div class="form-group amount-div">
                <%= label_tag(:amount, 'Amount', class: 'col-xs-12') %>
                <div class="col-xs-12">
                    <%= f.text_field :amount, class: 'form-control amount' %>
                    <%= f.hidden_field :financial_year_id, value: @current_financial_year.id %>
                </div>
            </div>
            <div class="form-group">
            <%= label_tag(:amount_in_words, 'Amount in Words', class: 'col-xs-12') %>
            <div class="col-xs-12">
                <%= f.text_area :amount_in_words,  class: 'form-control' %>
            </div>
            </div>
            <div class="form-group">
                <%= label_tag(:payment_voucher_id, 'Payment Voucher', class: 'col-xs-12') %>
                <div class="col-xs-12">
                <select name='petty_cash[payment_voucher_id]' class="form-control">
                    <% PaymentVoucher.order(created_at: :desc).each do |payment_voucher| %>
                    <option value="<%= payment_voucher.id %>"><%= payment_voucher.number %></option>
                    <% end %>
                </select>
                </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <%= submit_tag('SAVE', class: "btn btn-primary") %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/petty_cash/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-3 col-sm-5">
    <div class="panel">
      <header class="panel-heading">
        <h2 class="panel-title text-center">Petty Cash Details</h2>
      </header>
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped">
            <tr>
              <th>Amount</th>
              <td><%= @petty_cash.amount %></td>
            </tr>
            <tr>
              <th>Amount in Words</th>
              <td><%= @petty_cash.amount_in_words %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>