config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { sessions: "accounts/sessions",
    registrations: 'accounts/registrations' }

  match '/save_expenditure',  to: 'budgets#save_expenditure',  via: :post, as: :save_expenditure
  match '/save_revenue',  to: 'budgets#save_revenue',  via: :post, as: :save_revenue
  match '/approve_payment_voucher',  to: 'payment_vouchers#approve',  via: :post, as: :approve_payment_voucher
  match '/approve_petty_cash',  to: 'petty_cash_vouchers#approve',  via: :post, as: :approve_petty_cash
  match '/authorize_payment_voucher',  to: 'payment_vouchers#authorize',  via: :post, as: :authorize_payment_voucher
  match '/authorize_petty_cash',  to: 'petty_cash_vouchers#authorize',  via: :post, as: :authorize_petty_cash
  match '/accounting',  to: 'dashboard#index',  via: :get, as: :accounting_index

  root 'dashboard#index'
  resources :dashboard, only: [:index]
  resources :roles
  resources :financial_years do
    resources :budgets
    resources :revenues
    resources :petty_cash
    resources :petty_cash_vouchers
    resources :payment_vouchers
    resources :vouchers
  end
  resources :bank_accounts
  resources :code_categories do
    resources :codes do
      resources :sub_codes
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment_voucher.rb
class PaymentVoucher < ApplicationRecord
  include SharedTasks
  has_many :system_logs, as: :loggable, dependent: :destroy
  has_paper_trail
  belongs_to :financial_year
  has_one :voucher, as: :payment, dependent: :destroy
  has_many :petty_cash
  # accepts_nested_attributes_for :voucher
  after_create :create_voucher_number

  private

  def create_voucher_number
    financial_year = self.financial_year
    voucher_number = "PV/#{financial_year.name}/#{add_zeros(self.id)}"
    self.update(number: voucher_number)
  end
end

app/controllers/payment_vouchers_controller.rb
class PaymentVouchersController < ApplicationController
  include Printable
  before_action :set_paper_trail_whodunnit

  def new
    @payment_voucher = PaymentVoucher.new
    @codes = CodeCategory.expenses.sub_codes
  end

  def create
    @payment_voucher = PaymentVoucher.new(payment_voucher_params)
    if @payment_voucher.save
      save_voucher
      flash[:success] = "Successfully created a payment voucher(#{@payment_voucher.number})"
      notes = "Added a payment voucher: voucher number #{@payment_voucher.number} and id: #{@payment_voucher.id}"
      create_log('create', @payment_voucher, notes)
      respond_to do |format|
        format.html { redirect_to financial_year_payment_voucher_path(@current_financial_year,@payment_voucher)}
      end
    else
      flash[:error] = "Sorry please try again"
      puts @payment_voucher.errors.full_messages.to_sentence
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def approve
    payment_voucher = PaymentVoucher.find(params[:id])
    voucher = payment_voucher.voucher
    voucher.update(approved_by: current_account.id, approval_date: Time.now)
    flash[:success] = "Successfully approved"
    notes = "Approved payment Voucher #{payment_voucher.number}"
    create_log('create', payment_voucher, notes)
    redirect_to financial_year_payment_voucher_path(@current_financial_year, payment_voucher)
  end

  def authorize
    payment_voucher = PaymentVoucher.find(params[:id])
    voucher = payment_voucher.voucher
    voucher.update(authorized_by: current_account.id, authorization_date: Time.now)
    voucher.update_bank_account
    voucher.update_budget_expenditure
    flash[:success] = "Successfully authorized"
    notes = "Approved payment Voucher #{payment_voucher.number}"
    create_log('create', payment_voucher, notes)
    redirect_to financial_year_payment_voucher_path(@current_financial_year, payment_voucher)
  end

  def index
    @payment_vouchers = PaymentVoucher.all.where(financial_year_id: @current_financial_year.id)
  end

  def show
    @payment_voucher = PaymentVoucher.find(params[:id])
    @voucher = @payment_voucher.voucher
  end

  def print
    @payment_voucher = PaymentVoucher.find(params[:id])
    @voucher = @payment_voucher.voucher
    print_voucher(@payment_voucher)
  end

  private

  def payment_voucher_params
    params.require(:payment_voucher).permit(:financial_year_id)
  end

  def save_voucher
    code_amount_divisions = {}
    code_ids = params[:selected_codes].split(',')
    code_amounts = params[:selected_codes_amounts].split(',')
    code_ids.each do |code_id|
      index = code_ids.index(code_id)
      code_amount_divisions[code_id] = code_amounts[index]
    end
    voucher = Voucher.create(payee: params[:payee], amount: params[:amount],
      amount_in_words: params[:amount_in_words], details: params[:details],
      code_amount_divisions: code_amount_divisions, accounting_code_type: 'SubCode',
    created_by: current_account.id, payment_type: 'PaymentVoucher', cheque_no: params[:cheque_no],
    payment_id: @payment_voucher.id, bank_account_id: params[:bank_account_id])
  end
end

app/helpers/payment_vouchers_helper.rb
module PaymentVouchersHelper
end

app/views/payment_vouchers/index.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="panel">
       <div class="panel-body">
         <%= link_to 'New Payment Voucher', new_financial_year_payment_voucher_path(@current_financial_year) , class: 'btn btn-lg btn-primary' %>
       </div>
     </div>
   </div>
   <div class="col-md-12">
     <div class="panel">
       <header class="panel-heading">
         <h2 class="panel-title">Payment Vouchers</h2>
       </header>
       <div class="panel-body">
         <div class="table-responsive">
           <table class="table table-bordered table-hover table-striped">
             <thead>
               <tr>
                 <th>#</th>
                 <th>Number</th>
                 <th>Amount</th>
                 <th>Created By</th>
                 <th>Approved By</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <!--  Make sure that all vouchers are only for the current year -->
               <% @payment_vouchers.all.each do |payment_voucher| %>
                 <tr>
                   <td>#</td>
                   <td><%= link_to payment_voucher.number, financial_year_payment_voucher_path(@current_financial_year, payment_voucher) %></td>
                   <td><%= currency_formatter(payment_voucher.voucher.amount) %></td>
                   <td><%= find_account(payment_voucher.voucher.created_by) %></td>
                   <td><%= find_account(payment_voucher.voucher.approved_by) %></td>
                   <td></td>
                 </tr>
               <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payment_vouchers/new.html.erb
<div class="col-xs-12 col-sm-offset-3 col-sm-5">
    <div class="panel">
        <header class="panel-heading">
            <h2 class="panel-title text-center">Payment Voucher</h2>
        </header>
        <div class="panel-body">
          <%= form_for @payment_voucher, url: {action: "create"}, html: {id: 'payment-form', class: "form-horizontal"} do |f| %>
            <%= render 'shared/voucher_form', f: f, voucher_class: @payment_voucher.class.to_s %>
          <% end %>
        </div>
    </div>
</div>

app/views/payment_vouchers/show.html.erb
<div class="row">
  <% if !@voucher.approved_by %>
    <div class="col-xs-12 col-sm-offset-3 col-sm-5">
      <div class="panel">
        <div class="panel-body">
          <%= link_to 'Approve', approve_payment_voucher_path(id: @payment_voucher.id), class: 'btn btn-primary', method: :post %>
        </div>
      </div>
    </div>
  <% end %>
  <% if @voucher.approved_by && !@voucher.authorized_by %>
    <div class="col-xs-12 col-sm-offset-3 col-sm-5">
      <div class="panel">
        <div class="panel-body">
          <%= link_to 'Authorize', authorize_payment_voucher_path(id: @payment_voucher.id), class: 'btn btn-primary', method: :post %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-xs-12 col-sm-offset-3 col-sm-5">
    <div class="panel">
      <header class="panel-heading">
        <h2 class="panel-title text-center">Payment Voucher(<%= @payment_voucher.number %>)</h2>
      </header>
      <div class="panel-body">
        <%= render 'shared/voucher_details' %>
        <div>
          <%= link_to 'Print Voucher', financial_year_voucher_path(@payment_voucher.id, format: 'pdf', type: 'PaymentVoucher'), class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
</div>