config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { sessions: "accounts/sessions",
    registrations: 'accounts/registrations' }

  match '/save_expenditure',  to: 'budgets#save_expenditure',  via: :post, as: :save_expenditure
  match '/save_revenue',  to: 'budgets#save_revenue',  via: :post, as: :save_revenue
  match '/approve_payment_voucher',  to: 'payment_vouchers#approve',  via: :post, as: :approve_payment_voucher
  match '/approve_petty_cash',  to: 'petty_cash_vouchers#approve',  via: :post, as: :approve_petty_cash
  match '/authorize_payment_voucher',  to: 'payment_vouchers#authorize',  via: :post, as: :authorize_payment_voucher
  match '/authorize_petty_cash',  to: 'petty_cash_vouchers#authorize',  via: :post, as: :authorize_petty_cash
  match '/accounting',  to: 'dashboard#index',  via: :get, as: :accounting_index

  root 'dashboard#index'
  resources :dashboard, only: [:index]
  resources :roles
  resources :financial_years do
    resources :budgets
    resources :revenues
    resources :petty_cash
    resources :petty_cash_vouchers
    resources :payment_vouchers
    resources :vouchers
  end
  resources :bank_accounts
  resources :code_categories do
    resources :codes do
      resources :sub_codes
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  has_many :system_logs, as: :loggable, dependent: :destroy
  has_paper_trail
  has_many :bank_account_revenue_types
  has_many :vouchers

  def add_balance(increment)
    increment = BigDecimal.new(increment)
    bank_balance = balance
    bank_balance = 0.0 if bank_balance.nil?
    bank_balance = BigDecimal.new(bank_balance, 2)
    bank_balance += increment
    self.update(balance: bank_balance)
    puts "Debugging"
    puts "#{increment} - #{bank_balance}"
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_paper_trail_whodunnit

  def new
    @bank_account = BankAccount.new
  end

  def create
    bank_account = BankAccount.new(bank_account_params)
    if bank_account.save
      #to be implemented
      Code.revenue_codes.each do |code|
        code.revenue_division.percentage_divisions["#{bank_account.id}"] = "0"
        code.revenue_division.save
      end
      notes = "Added a Bank Account with name: #{bank_account.name} and id: #{bank_account.id}"
      create_log('create', bank_account, notes)
    else
      #to be implemented
      puts bank_account.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to bank_accounts_path}
    end
  end

  def edit
    @bank_account = BankAccount.find(params[:id])
  end

  def update
    bank_account = BankAccount.find(params[:id])
    increment = params[:increment].gsub(",","")
    bank_account.add_balance(increment)
    flash[:success] = "Successfully added balance"
    notes = "Added a Balance of #{increment} to Bank Account : #{bank_account.name} and id: #{bank_account.id}"
    create_log('create', bank_account, notes)

    respond_to do |format|
      format.html { redirect_to bank_accounts_path}
    end
  end

  def index
    @bank_accounts = BankAccount.all
  end

  private

  def bank_account_params
    params.require(:bank_account).permit(:name, :number)
  end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/edit.html.erb
<div class="col-xs-12 col-sm-offset-4 col-sm-4">
    <div class="panel">
        <header class="panel-heading">
            <h2 class="panel-title text-center">Edit Balance (Account Name: <%= @bank_account.name %>)</h2>
        </header>
        <div class="panel-body">
          <%= form_for @bank_account, url: {action: "update"}, html: {class: "form-horizontal bank-account-form"} do |f| %>
            <div class="form-group amount-div">
              <%= label_tag(:name, 'Add Balance', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= text_field_tag :increment, nil, class: 'form-control amount' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <%= submit_tag('SAVE', class: "btn btn-primary") %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/bank_accounts/index.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="panel">
       <div class="panel-body">
         <%= link_to 'New Bank Account', new_bank_account_path , class: 'btn btn-lg btn-primary' %>
       </div>
     </div>
   </div>
   <div class="col-md-12">
     <div class="panel">
       <header class="panel-heading">
         <h2 class="panel-title">Bank Accounts</h2>
       </header>
       <div class="panel-body">
         <div class="table-responsiv">
           <table class="table table-bordered table-hover table-striped">
             <thead>
               <tr>
                 <th>#</th>
                 <th>Account Name</th>
                 <th>Account Number</th>
                 <th>Bank Balance</th>
                 <th class="text-center">Actions</th>
               </tr>
             </thead>
             <tbody>
               <% @bank_accounts.each do |bank_account| %>
                 <tr>
                   <td></td>
                   <td><%= bank_account.name %></td>
                   <td><%= bank_account.number %></td>
                   <td><%= currency_formatter(bank_account.balance) %></td>
                   <td>
                     <div class="dropdown text-center">
                       <a id="bank_account_<%= bank_account.id%>" href="javascript:;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                         <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
                       </a>
                      <ul class="dropdown-menu pull-right text-center" aria-labelledby="bank_account_<%= bank_account.id%>">
                        <li><%= link_to 'Add Balance', edit_bank_account_path(bank_account) %></li>
                        <li><%= link_to 'Reconciliation', "javascript:;" %></li>
                      </ul>
                    </div>
                   </td>
                 </tr>
               <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bank_accounts/new.html.erb
<div class="col-xs-12 col-sm-offset-4 col-sm-4">
    <div class="panel">
        <header class="panel-heading">
            <h2 class="panel-title text-center">Add A Bank Account</h2>
        </header>
        <div class="panel-body">
          <%= form_for @bank_account, url: {action: "create"}, html: {class: "form-horizontal"} do |f| %>
            <div class="form-group">
              <%= label_tag(:name, 'Account Name', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag(:number, 'Account Number', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= f.text_field :number, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <%= submit_tag('SAVE', class: "btn btn-primary") %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>