config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts, controllers: { sessions: "accounts/sessions",
    registrations: 'accounts/registrations' }

  match '/save_expenditure',  to: 'budgets#save_expenditure',  via: :post, as: :save_expenditure
  match '/save_revenue',  to: 'budgets#save_revenue',  via: :post, as: :save_revenue
  match '/approve_payment_voucher',  to: 'payment_vouchers#approve',  via: :post, as: :approve_payment_voucher
  match '/approve_petty_cash',  to: 'petty_cash_vouchers#approve',  via: :post, as: :approve_petty_cash
  match '/authorize_payment_voucher',  to: 'payment_vouchers#authorize',  via: :post, as: :authorize_payment_voucher
  match '/authorize_petty_cash',  to: 'petty_cash_vouchers#authorize',  via: :post, as: :authorize_petty_cash
  match '/accounting',  to: 'dashboard#index',  via: :get, as: :accounting_index

  root 'dashboard#index'
  resources :dashboard, only: [:index]
  resources :roles
  resources :financial_years do
    resources :budgets
    resources :revenues
    resources :petty_cash
    resources :petty_cash_vouchers
    resources :payment_vouchers
    resources :vouchers
  end
  resources :bank_accounts
  resources :code_categories do
    resources :codes do
      resources :sub_codes
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/financial_year.rb
class FinancialYear < ApplicationRecord
  has_many :system_logs, as: :loggable, dependent: :destroy
  has_paper_trail
  has_one :budget
  has_many :payment_vouchers
  has_many :revenues
  acts_as_paranoid

  validates :name,        presence: true
  validates :start_date,  presence: true
  validates :end_date,    presence: true
  validates :is_current,  presence: true


  def self.current
    FinancialYear.find_by(is_current: 'yes')
  end
end

app/controllers/financial_years_controller.rb
class FinancialYearsController < ApplicationController
  

  def new
    @financial_year = FinancialYear.new
  end

  def create
    financial_year = FinancialYear.new(financial_year_params)
    if financial_year.save
      #to be implemented
      notes = "Added a financial year with name: #{financial_year.name} and id: #{financial_year.id}"
      create_log('create', financial_year, notes)
    else
      #to be implemented
      puts financial_year.errors.full_messages.to_sentence
    end

    respond_to do |format|
      format.html { redirect_to financial_years_path}
    end
  end

  def show
    @financial_year = FinancialYear.find(params[:id])
  end

  def index
    @financial_years = FinancialYear.all
  end

  private

  def financial_year_params
    params.require(:financial_year).permit(:name, :start_date, :end_date, :is_current)
  end
end

app/helpers/financial_years_helper.rb
module FinancialYearsHelper
end

app/views/financial_years/index.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="panel">
       <div class="panel-body">
         <%= link_to 'New Year', new_financial_year_path , class: 'btn btn-lg btn-primary' %>
       </div>
     </div>
   </div>
   <div class="col-md-12">
     <div class="panel">
       <header class="panel-heading">
         <h2 class="panel-title">Financial Years</h2>
       </header>
       <div class="panel-body">
         <div class="table-responsive">
           <table class="table table-bordered table-hover table-striped">
             <thead>
               <tr>
                 <th>#</th>
                 <th>Name</th>
                 <th>Start Date</th>
                 <th>End Date</th>
                 <th>Current</th>
               </tr>
             </thead>
             <tbody>
               <% @financial_years.each do |financial_year| %>
                 <tr>
                   <td></td>
                   <td><%= link_to financial_year.name, financial_year_path(financial_year) %></td>
                   <td><%= date_formatter(financial_year.start_date) %></td>
                   <td><%= date_formatter(financial_year.end_date) %></td>
                   <td>
                     <%= financial_year.is_current %>
                   </td>
                 </tr>
               <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/financial_years/new.html.erb
<div class="col-xs-12 col-sm-offset-4 col-sm-4">
    <div class="panel">
        <header class="panel-heading">
            <h2 class="panel-title text-center">Add A Financial Year</h2>
        </header>
        <div class="panel-body">
          <%= form_for @financial_year, url: {action: "create"}, html: {class: "form-horizontal"} do |f| %>
            <div class="form-group">
              <%= label_tag(:name, 'Name', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag(:start_date, 'Start Date', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= f.text_field :start_date, class: 'form-control date-ranges' %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag(:end_date, 'End Date', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <%= f.text_field :end_date, class: 'form-control date-ranges' %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag(:is_current, 'Is Current Year', class: 'col-xs-12') %>
              <div class="col-xs-12">
                <label class="radio-inline">
                  <input type="radio" name="financial_year[is_current]" id="is_current_true" value="yes"> Yes
                </label>
                <label class="radio-inline">
                  <input type="radio" name="financial_year[is_current]" id="is_current_false" value="no"> No
                </label>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <%= submit_tag('SAVE', class: "btn btn-primary") %>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/financial_years/show.html.erb
<div class="row">
   <div class="col-md-12">
     <div class="panel">
       <div class="panel-body">
         <%= link_to 'Add Budget', new_financial_year_budget_path(@financial_year) , class: 'btn btn-lg btn-primary' %>
      </div>
    </div>
   </div>
   <div class="col-md-12">
     <div class="panel">
       <header class="panel-heading">
         <h2 class="panel-title">Details</h2>
       </header>
       <div class="panel-body">
       </div>
     </div>
   </div>
 </div>